/*
 * This source file was generated by the Gradle 'init' task
 */
package com.irctc;

import java.util.Scanner;


public class  App {
    public static void main(String[] args) {
        System.out.println("Running Train booking system: ");
        Scanner scanner = new Scanner(System.in);

    }
}
